name = "spinmachocasino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachocasino.pt"
HMAC_KEY = "e6127956e5983aff946c93e4e82ee5b9e282410036ed21f6321d53ea2678287d"
COOKIE_NAME = "h8t"
PLAY_PATH = "visit"
BUTTON_ID = "p8caa0ade007b02aab6c848b3580d50d4"
GATE_SALT = "b660245ec548988e"
